name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests with Vitest
        run: npm run test

      - name: Run test with ESLint
      - run: npm run ESLint

      - name: Run ESLint
        run: npm run lint

      # FOR IT TO WORK WITH GITHUB Actions and push to Docker registry do the following
      # In your repo settings, go to Settings → Secrets and variables → Actions → Secrets, and add:
      # DOCKER_USERNAME – your Docker Hub username
      # DOCKER_PASSWORD – a Docker Hub personal access token

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/iot-app:latest .

      # - name: Push Docker image to Docker Hub
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/iot-app:latest
